### ISSUE TITLE
Prometheus service annotations and basic auth

### ISSUE THREAD

**Issue by chazapp** [chazapp/incidents-k8s#11]
The API should be scraped by Prometheus using service annotations such as:
```
# service.yml
kind: Service
metadata:
  annotations:
     prometheus.io/scrape: "true"
     prometheus.io/path: "/metrics/"
    # creds ?
````

The problem is that the /metrics/ endpoint is protected by API authentication. Prometheus should provide a way to pass basic auth credentials via service annotation, but I was unable to find any Prometheus docs about kubernetes annotations. 

As a workaround for now, the Prometheus configmap for `prometheus.yml` has been edited to add a static scrape_config that targets the API service, but this feature should not be outside the scope of this repository.
